version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: web
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    image: php:8.2-fpm-bullseye
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
  postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
      volumes:
        - ./postgres-data/data:/var/lib/postgresql/data
        - ./init:/docker-entrypoint-initdb.d
volumes:
  postgres-data:
